### ISSUE TITLE
A Simple TODO App in html,css,js is missing

### ISSUE THREAD

**Issue by Priya-shan** [vishnu2k60/HacktoberFest2021#59]
Hii @vishnu2k60
I would like to contribute Todo App code in JS Please assign me this task !!

**Comment by devikavarshney** [comment]
@vishnu2k60 I can improve the UI design of this TO DO app. please assign this work to me .

**Comment by devikavarshney** [comment]
@vishnu2k60 I was doing the changes.

**Comment by devikavarshney** [comment]
@vishnu2k60 Can you confirm if I Can still improve the UI design of the App??
